Repository Team-Ampersand/Dotori-iOS, pull requests merged in 2023-08, with the labels that each got.

#141 🔀 :: [#140] iPad에서 ActionSheet를 Alert로 present
  Projects/Feature/HomeFeature/Sources/Moordinator/HomeMoordinator.swift
  Projects/Feature/MusicFeature/Sources/Moordinator/MusicMoordinator.swift
Labels: 0️⃣Priority: Critical, 🐞 BugFix

#143 🔀 :: [#142] ModalViewController의 dismiss가 subviews를 눌러도 적용되는 현상
  Projects/Feature/FilterSelfStudyFeature/Sources/Scene/FilterSelfStudyViewController.swift
  Projects/Shared/CombineUtility/Sources/UIGestureRecognizer/UIGestureRecognizer+publisher.swift
Labels: 0️⃣Priority: Critical, 🐞 BugFix

#147 🔀 :: [#144] 회원탈퇴 기능 추가
  Projects/Core/Networking/Interface/Endpoint/DotoriRestAPIDomain.swift
  Projects/Domain/AuthDomain/Sources/DataSource/Remote/AuthEndpoint.swift
  Projects/Domain/AuthDomain/Sources/DataSource/Remote/RemoteAuthDataSourceImpl.swift
  Projects/Domain/UserDomain/Interface/DataSource/RemoteUserDataSource.swift
  Projects/Domain/UserDomain/Interface/Repository/UserRepository.swift
  Projects/Domain/UserDomain/Interface/UseCase/WithdrawalUseCase.swift
  Projects/Domain/UserDomain/Sources/Assembly/UserDomainAssembly.swift
  Projects/Domain/UserDomain/Sources/DataSource/Local/LocalUserDataSourceImpl.swift
  Projects/Domain/UserDomain/Sources/DataSource/Remote/RemoteUserDataSourceImpl.swift
  Projects/Domain/UserDomain/Sources/DataSource/Remote/UserEndpoint.swift
  Projects/Domain/UserDomain/Sources/Repository/UserRepositoryImpl.swift
  Projects/Domain/UserDomain/Sources/UseCase/WithdrawalUseCaseImpl.swift
  Projects/Domain/UserDomain/Testing/DataSource/RemoteUserDataSourceSpy.swift
  Projects/Domain/UserDomain/Testing/Repository/UserRepositorySpy.swift
  Projects/Domain/UserDomain/Testing/UseCase/WithdrawalUseCaseSpy.swift
  Projects/Domain/UserDomain/Tests/UserRepositoryTest.swift
  Projects/Feature/HomeFeature/Demo/Sources/AppDelegate.swift
  Projects/Feature/HomeFeature/Sources/Assembly/HomeAssembly.swift
  Projects/Feature/HomeFeature/Sources/Factory/HomeFactoryImpl.swift
  Projects/Feature/HomeFeature/Sources/Scene/HomeViewController.swift
  Projects/Feature/HomeFeature/Sources/Scene/Store/HomeStore.swift
  Projects/Feature/HomeFeature/Tests/HomeFeatureTest.swift
  Projects/UserInterface/Localization/Resources/en.lproj/Home.strings
  Projects/UserInterface/Localization/Resources/ko.lproj/Home.strings
Labels: 0️⃣Priority: Critical, ✨ Feature

#155 🔀 :: [#151] README 작성
  README.md
  graph.png
Labels: 1️⃣Priority: High, 📃 Docs

#156 🔀 :: [#62] 자동화 배포 구축
  .github/workflows/AppStore.yml
  .github/workflows/CI.yml
  .gitignore
  Gemfile
  Gemfile.lock
  Makefile
  Plugin/EnvironmentPlugin/ProjectDescriptionHelpers/ProjectEnvironment.swift
  Projects/App/Project.swift
  Projects/App/ShareExtension/Support/Info.plist
  Projects/App/Support/Info.plist
  Projects/Core/Networking/Project.swift
  Projects/Domain/MealDomain/Project.swift
  Scripts/GenerateModule.swift
  Tuist/ProjectDescriptionHelpers/Enum/GenerateEnvironment.swift
  Tuist/ProjectDescriptionHelpers/Project+Template.swift
  Tuist/ProjectDescriptionHelpers/SettingsDictionary/CodeSign.swift
  Tuist/ProjectDescriptionHelpers/Target/TargetSpec.swift
  Tuist/Signing/Dotori.PROD.mobileprovision.gpg
  Tuist/Signing/Dotori.p12.encrypted
  Tuist/Signing/distribution.cer.encrypted
  Tuist/master.key.gpg
  XCConfig.zip.gpg
  fastlane/.env.default.gpg
  fastlane/AppStoreAPIKey.json.gpg
  fastlane/Appfile
  fastlane/Deliverfile
  fastlane/Fastfile
  fastlane/Pluginfile
  fastlane/README.md
  fastlane/metadata/copyright.txt
  fastlane/metadata/ko/apple_tv_privacy_policy.txt
  fastlane/metadata/ko/description.txt
  fastlane/metadata/ko/keywords.txt
  fastlane/metadata/ko/marketing_url.txt
  fastlane/metadata/ko/name.txt
  fastlane/metadata/ko/privacy_url.txt
  fastlane/metadata/ko/promotional_text.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/ko/subtitle.txt
  fastlane/metadata/ko/support_url.txt
  fastlane/metadata/primary_category.txt
  fastlane/metadata/primary_first_sub_category.txt
  fastlane/metadata/primary_second_sub_category.txt
  fastlane/metadata/secondary_category.txt
  fastlane/metadata/secondary_first_sub_category.txt
  fastlane/metadata/secondary_second_sub_category.txt
  fastlane/screenshots/README.txt
  graph.png
Labels: 🌏 Deploy, 2️⃣Priority: Medium

#158 🔀 :: [#157] CD 이후 버전 변경사항 master에 반영
  .github/workflows/AppStore.yml
Labels: 🌏 Deploy, 0️⃣Priority: Critical, 🐞 BugFix

#160 🔀 :: [#159] 키체인에 p12 프로필 import
  .github/workflows/AppStore.yml
  Projects/App/Project.swift
  Tuist/ProjectDescriptionHelpers/Project+Template.swift
  Tuist/ProjectDescriptionHelpers/SettingsDictionary/CodeSign.swift
  Tuist/ProjectDescriptionHelpers/Target/TargetSpec.swift
  Tuist/Signing/Dotori.cer.encrypted
  Tuist/Signing/Dotori.p12.encrypted
  Tuist/Signing/DotoriShareExtension.PROD.mobileprovision.gpg
  Tuist/Signing/distribution.cer.encrypted
  fastlane/Fastfile
Labels: 🌏 Deploy, 0️⃣Priority: Critical, 🐞 BugFix

#163 🔀 :: [#154] 인원 수정 기능 숨겨두기
  Projects/Feature/HomeFeature/Sources/Moordinator/HomeMoordinator.swift
  Projects/Feature/HomeFeature/Sources/Scene/Enums/MassageStatusType+button.swift
  Projects/Feature/HomeFeature/Sources/Scene/Enums/SelfStudyStatusType+button.swift
  Projects/Feature/HomeFeature/Sources/Scene/HomeViewController.swift
  Projects/Feature/HomeFeature/Sources/Scene/Store/HomeStore.swift
  Scripts/.swiftlint.yml
Labels: 0️⃣Priority: Critical, ⚡️ Simple

#172 🔀 :: [#168] 인원 수정 UI 변경
  Projects/Feature/HomeFeature/Demo/Sources/AppDelegate.swift
  Projects/Feature/HomeFeature/Sources/Scene/Enums/MassageStatusType+button.swift
  Projects/Feature/HomeFeature/Sources/Scene/HomeViewController.swift
  Projects/Feature/HomeFeature/Sources/Scene/Store/HomeStore.swift
  Projects/Feature/HomeFeature/Sources/Scene/View/ApplicationCardView.swift
  Projects/Feature/HomeFeature/Sources/Scene/View/MealCardView.swift
  Projects/Feature/NoticeFeature/Sources/Scene/NoticeViewController.swift
  Projects/UserInterface/DesignSystem/Resources/DotoriIcon/DotoriIcon.xcassets/MiniChevronLeft.imageset/Contents.json
  Projects/UserInterface/DesignSystem/Resources/DotoriIcon/DotoriIcon.xcassets/MiniChevronLeft.imageset/mini.chevron.left.svg
  Projects/UserInterface/DesignSystem/Resources/DotoriIcon/DotoriIcon.xcassets/MiniChevronRight.imageset/Contents.json
  Projects/UserInterface/DesignSystem/Resources/DotoriIcon/DotoriIcon.xcassets/MiniChevronRight.imageset/mini.chevron.right.svg
  Projects/UserInterface/DesignSystem/Resources/DotoriIcon/DotoriIcon.xcassets/Refresh.imageset/Contents.json
  Projects/UserInterface/DesignSystem/Resources/DotoriIcon/DotoriIcon.xcassets/Refresh.imageset/refresh.svg
  Projects/UserInterface/DesignSystem/Resources/DotoriIcon/DotoriIcon.xcassets/Setting.imageset/Contents.json
  Projects/UserInterface/DesignSystem/Resources/DotoriIcon/DotoriIcon.xcassets/Setting.imageset/setting.svg
  Projects/UserInterface/DesignSystem/Sources/Icons/DotoriIcon.swift
  Projects/UserInterface/Localization/Resources/en.lproj/Home.strings
  Projects/UserInterface/Localization/Resources/ko.lproj/Home.strings
Labels: 0️⃣Priority: Critical, ✨ Feature

#179 🔀 :: [#162] CD 무한 로딩 문제 해결
  .github/workflows/AppStore.yml
  .github/workflows/AppStore/Decode.sh
  .github/workflows/AppStore/Deploy.sh
  .github/workflows/AppStore/Keychain.sh
  .github/workflows/AppStore/ReleasePR.sh
  fastlane/Fastfile
Labels: 🌏 Deploy, 1️⃣Priority: High

#175 🔀 :: [#174] 의존성이 없음에도 import를 하는 코드 제거
  Projects/Feature/FilterSelfStudyFeature/Sources/Scene/FilterSelfStudyViewController.swift
Labels: 🐞 BugFix, 1️⃣Priority: High

#182 🔀 :: [#181] ShareExtension 버그 해결
  Projects/App/ShareExtension/Sources/DotoriShareViewController.swift
  Projects/App/ShareExtension/Support/Info.plist
Labels: 0️⃣Priority: Critical, 🐞 BugFix

#183 🔀 :: 1.2.1 release
  .github/workflows/AppStore.yml
  Projects/App/Support/Info.plist
  Tuist/Signing/Dotori.cer.encrypted
  Tuist/Signing/Dotori.p12.encrypted
  fastlane/metadata/ko/release_notes.txt
Labels: 🌏 Deploy

#193 🔀 :: [#86] GitHooks 구성
  .gitconfig
  .githooks/pre-commit
  Makefile
  Scripts/Setup.sh
Labels: 3️⃣Priority: Low, ⚙ Setting
