Repository Team-Ampersand/Dotori-iOS, pull requests merged in 2023-05, with the labels that each got.

#13 🔀 :: DesignSystem DotoriCheckBox 추가
  Projects/Core/DesignSystem/Resources/DotoriIcon/DotoriIcon.xcassets/CheckMark.imageset/CheckMark 1.svg
  Projects/Core/DesignSystem/Resources/DotoriIcon/DotoriIcon.xcassets/CheckMark.imageset/CheckMark 2.svg
  Projects/Core/DesignSystem/Resources/DotoriIcon/DotoriIcon.xcassets/CheckMark.imageset/CheckMark.svg
  Projects/Core/DesignSystem/Resources/DotoriIcon/DotoriIcon.xcassets/CheckMark.imageset/Contents.json
  Projects/Core/DesignSystem/Sources/CheckBox/DotoriCheckBox.swift
  Projects/Core/DesignSystem/Sources/Icons/DotoriIcon.swift
Labels: 2️⃣Priority: Medium, ✨ Feature

#17 🔀 :: Then 디펜던시를 Configure로 변경
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+Target.swift
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/Feature/SigninFeature/Sources/Scene/SigninViewController.swift
  Projects/Shared/GlobalThirdPartyLibrary/Project.swift
  Projects/Shared/Then/Project.swift
  Projects/Shared/Then/Sources/Then.swift
  Projects/Shared/Then/Tests/ThenTest.swift
  Projects/UserInterface/DesignSystem/Project.swift
  Projects/UserInterface/DesignSystem/Sources/CheckBox/DotoriCheckBox.swift
  Projects/UserInterface/DesignSystem/Sources/TextField/DotoriIconTextField.swift
  Projects/UserInterface/DesignSystem/Sources/Toast/DotoriToast.swift
  Tuist/Dependencies.swift
Labels: ⚙ Setting, 2️⃣Priority: Medium, ⚡️ Simple

#20 🔀 :: CI 구축
  .github/workflows/CI.yml
  .github/workflows/CachingTuistDependencies.yml
  .gitignore
  Projects/Domain/BaseDomain/Project.swift
  XCConfig/Shared.xcconfig
Labels: ⚙ Setting, 1️⃣Priority: High

#23 💚 :: Discord Mention after failed to CI
  .github/workflows/CI.yml
Labels: 1️⃣Priority: High, ⚡️ Simple

#27 🔀 :: 상태관리 아키텍처 마이그레이션
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  Projects/Feature/BaseFeature/Project.swift
  Projects/Feature/BaseFeature/Sources/Base/BaseStore.swift
  Projects/Feature/BaseFeature/Sources/Base/BaseViewController.swift
  Projects/Feature/BaseFeature/Sources/Protocol/HasCancellableBag.swift
  Projects/Feature/SigninFeature/Sources/Scene/SigninStore.swift
  Projects/Feature/SigninFeature/Sources/Scene/SigninViewController.swift
  Projects/Shared/CombineUtility/Sources/Publisher/Publisher+sink.swift
  Tuist/Dependencies.swift
Labels: 🔨 Refactor, ⚙ Setting, 0️⃣Priority: Critical

#29 🔀 :: CODEOWNERS 설정
  .github/CODEOWNERS
Labels: 0️⃣Priority: Critical, ✨ Feature

#28 🔀 :: 모듈 의존성 경로 방식 변경
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+Target.swift
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/TargetDependency+ModulePaths.swift
  Projects/App/Project.swift
  Projects/Domain/AuthDomain/Project.swift
  Projects/Domain/BaseDomain/Project.swift
  Projects/Feature/BaseFeature/Project.swift
  Projects/Feature/MainFeature/Project.swift
  Projects/Feature/RenewalPasswordFeature/Project.swift
  Projects/Feature/RootFeature/Project.swift
  Projects/Feature/SigninFeature/Project.swift
  Projects/Feature/SignupFeature/Project.swift
  Projects/Shared/GlobalThirdPartyLibrary/Project.swift
  Projects/UserInterface/DesignSystem/Project.swift
  Scripts/GenerateModule.swift
Labels: 🔨 Refactor, 1️⃣Priority: High

#33 🔀 :: Script 실행 중 취소 가능하게 변경
  Scripts/CodeSigning.swift
  Scripts/GenerateModule.swift
  Scripts/InitEnvironment.swift
  Scripts/NewDependency.swift
Labels: 🔨 Refactor, 2️⃣Priority: Medium, ⚡️ Simple

#32 🔀 :: IQKeyboardManager 적용
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  Projects/App/Sources/Application/AppDelegate.swift
  Projects/Feature/BaseFeature/Project.swift
  Tuist/Dependencies.swift
Labels: ⚙ Setting, 2️⃣Priority: Medium
