Repository Team-Ampersand/Dotori-iOS, pull requests merged in 2024-03, with the labels that each got.

#224 🔀 :: [#223] 세로모드로 고정되게 수정
  Projects/App/ShareExtension/Support/Info.plist
  Projects/App/Support/Info.plist
  Projects/Feature/HomeFeature/Sources/Scene/View/MealContentStackView.swift
Labels: 1️⃣Priority: High, ⚡️ Simple

#226 🔀 :: [#225] 토큰 재발급 API 수정
  Projects/Core/Networking/Interface/Interceptor/Jwt/JwtAuthorizable.swift
Labels: 🔨 Refactor, 0️⃣Priority: Critical, ⚡️ Simple

#228 🔀 :: [#227] createdTime format 수정
  Projects/Domain/MusicDomain/Sources/DTO/Response/FetchMusicListResponseDTO.swift
Labels: 🔨 Refactor, 0️⃣Priority: Critical, ⚡️ Simple

#232 🔀 :: [#231] 아이패드 가로모드 지원
  Projects/App/Support/Info.plist
Labels: 0️⃣Priority: Critical, 🐞 BugFix, ⚡️ Simple

#234 📝 :: 1.2.3 released
  Projects/App/Support/Info.plist
  Tuist/Signing/Dotori.cer.encrypted
  Tuist/Signing/Dotori.p12.encrypted
  fastlane/metadata/ko/release_notes.txt
Labels: ⚙ Setting

#235 🔀 :: [#3] Auth파트 테스트 코드 작성
  Projects/Domain/AuthDomain/Testing/DataSource/LocalAuthDataSourceSpy.swift
  Projects/Domain/AuthDomain/Testing/DataSource/RemoteAuthDataSourceSpy.swift
  Projects/Domain/AuthDomain/Testing/UseCase/SigninUseCaseSpy.swift
  Projects/Domain/AuthDomain/Tests/Repository/AuthRepositoryTests.swift
  Projects/Domain/AuthDomain/Tests/UseCase/SigninUseCaseTests.swift
  Projects/Feature/SigninFeature/Project.swift
  Projects/Feature/SigninFeature/Tests/SigninFeatureTest.swift
  Projects/Feature/SigninFeature/Tests/SigninFeatureTests.swift
  Projects/Shared/CombineUtility/Sources/Publisher/Publisher+toAsyncStream.swift
Labels: 3️⃣Priority: Low, ✅ Test
