Repository Team-Ampersand/Dotori-iOS, pull requests merged in 2024-04, with the labels that each got.

#240 🔀 :: [#237] 자습신청자 페이지, 안마의자 신청자 페이지에서 프로필 이미지 보여주기
  Projects/Domain/MassageDomain/Interface/Entity/MassageRankEntity.swift
  Projects/Domain/MassageDomain/Sources/DTO/Response/FetchMassageRankListResponseDTO.swift
  Projects/Domain/MassageDomain/Tests/FetchMassageRankListUseCaseTests.swift
  Projects/Domain/MassageDomain/Tests/MassageRepositoryTests.swift
  Projects/Domain/SelfStudyDomain/Interface/Entity/SelfStudyRankEntity.swift
  Projects/Domain/SelfStudyDomain/Sources/DTO/Response/FecthSelfStudyRankListResponseDTO.swift
  Projects/Domain/SelfStudyDomain/Tests/FetchSelfStudyRankListUseCaseTests.swift
  Projects/Feature/HomeFeature/Demo/Sources/AppDelegate.swift
  Projects/Feature/HomeFeature/Sources/Assembly/HomeAssembly.swift
  Projects/Feature/HomeFeature/Sources/Factory/HomeFactoryImpl.swift
  Projects/Feature/HomeFeature/Sources/Scene/HomeViewController.swift
  Projects/Feature/HomeFeature/Sources/Scene/Store/HomeStore+State.swift
  Projects/Feature/HomeFeature/Sources/Scene/Store/HomeStore.swift
  Projects/Feature/HomeFeature/Tests/HomeFeatureTest.swift
  Projects/Feature/MassageFeature/Demo/Sources/AppDelegate.swift
  Projects/Feature/MassageFeature/Sources/Scene/View/MassageCell.swift
  Projects/Feature/MassageFeature/Tests/MassageFeatureTest.swift
  Projects/Feature/SelfStudyFeature/Demo/Sources/AppDelegate.swift
  Projects/Feature/SelfStudyFeature/Sources/Scene/SelfStudyStore.swift
  Projects/Feature/SelfStudyFeature/Sources/Scene/View/SelfStudyCell.swift
  Projects/UserInterface/DesignSystem/Sources/CardView/AppliedStudentCardView.swift
Labels: ✨ Feature, 1️⃣Priority: High

#238 🔀 :: [#237] 본인의 프로필 이미지를 메인 페이지에 보여주기
  Projects/Feature/HomeFeature/Sources/Scene/HomeViewController.swift
  Projects/Feature/HomeFeature/Sources/Scene/Store/HomeStore+State.swift
  Projects/Feature/HomeFeature/Sources/Scene/Store/HomeStore.swift
  Projects/Shared/CombineUtility/Sources/Publisher/Publisher+async.swift
  Projects/Shared/CombineUtility/Sources/Publisher/Publisher+catchToNever.swift
Labels: ✨ Feature, 1️⃣Priority: High, ⚡️ Simple

#241 🔀 :: [#229] Tuist 버전 업그레이드
  .github/workflows/CI.yml
  .mise.toml
  .tuist-version
  Makefile
  Plugin/EnvironmentPlugin/ProjectDescriptionHelpers/ProjectEnvironment.swift
  Projects/App/Project.swift
  Tuist/Package.resolved
  Tuist/Package.swift
  Tuist/ProjectDescriptionHelpers/Project+Template.swift
  Tuist/ProjectDescriptionHelpers/Target/TargetSpec.swift
Labels: 🔨 Refactor, ⚙ Setting, 0️⃣Priority: Critical, ⚡️ Simple

#244 🔀 :: [#233] runner 환경 macos14 업그레이드
  .github/workflows/AppStore.yml
Labels: ⚙ Setting
